version: '3'

services:
  web:
    restart: always
    build: ./server
    image: jewelry-store:latest
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - web-django:/srv/src/
      - web-static:/src/src/static
    env_file: .env
    environment:
      - DEBUG=true
      - POSTGRES_PASSWORD=postgres
    command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgres      
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - bootstrap.check=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
  esdata:
