version: '3'

services:
  web:
    restart: always
    build: ./web
    image: jewelry-store:latest
    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - app
    volumes:
      - web-react:/app/web
    environment:
      - DEBUG=true
    command: npm start

  app:
    restart: always
    build: ./server
    image: jewelry-app:latest
    expose:
      - "8000"
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
      - redis:redis
    volumes:
      - ./server/src/:/srv/server/
      - django-src:/src/server/src/
      - django-static:/srv/server/src/static
    env_file: .env
    environment:
      - DEBUG=true
      - POSTGRES_PASSWORD=postgres
    command: /usr/local/bin/gunicorn server.wsgi:application -w 2 -b 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - django-static:/www/static
    links:
      - web:web
      - app:app

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  elasticsearch:
    image: elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
      - bootstrap.check=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  web-react:
  django-src:
  django-static:
  pgdata:
  redisdata:
  esdata:
